server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/automobile-sales-mall
    username: root
    password: jzl123456
    driver-class-name: com.mysql.jdbc.Driver
  # SpringMVC视图解析器配置
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.school.design.automobile_sales_mall.entity

